/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package final_assignment;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {

    @Test
    public void testPred() {
        int[] inputArray = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10};
        double alpha = 0.3;
        Skewed_Binary_Search.Sorted_Array sortedArray = new Skewed_Binary_Search.Sorted_Array(inputArray, alpha);

        // Test for an existing element
        int existingElement = 5;
        assertEquals(existingElement, sortedArray.Pred(existingElement));

        // Test for a non-existing element
        int nonExistingElement = 15;
        int expectedResultForNonExisting = Integer.MAX_VALUE;
        assertEquals(expectedResultForNonExisting, sortedArray.Pred(nonExistingElement));

        // Add more test cases based on the specific behavior of your Pred method
    }
}