/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package final_assignment;

import java.util.Arrays;

public class Skewed_Binary_Search {

    static class Sorted_Array {
    private int[] S;
    private double alpha;

    public Sorted_Array(int[] input, double alpha){
        Arrays.parallelSort(input);
        this.S = input;
        this.alpha = alpha;
    }

    public int Pred(int x) {
        int left = 0;
        int right = S.length - 1;
        int y = Integer.MAX_VALUE;

        while (left <= right) {
            int mid = left + (int) Math.round((right - left) * alpha);

            if (S[mid] < x) {
                left = mid + 1;
            } else if (S[mid] > x) {
                right = mid - 1;
            } else if (S[mid] == x) {
                y = S[mid];
                break;
            }
        }
        return y;
        
    }
    public static void main(String[] args) {       
        int[] inputArray = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10};
        double alpha = 0.3;
        int existingElement = 5;
        Skewed_Binary_Search.Sorted_Array testSortedArray = new Sorted_Array(inputArray, alpha);
        System.out.println(testSortedArray.Pred(existingElement));
    }
}}

